### ISSUE TITLE
不能对 amo 等限制页面生效

### ISSUE THREAD

**Issue by ivysrono** [zhcong/firefox-qrcoder#1]
我知道 WebExtension 对这些特殊页面的限制，但[QR Coder :: Firefox 附加组件](https://addons.mozilla.org/zh-CN/firefox/addon/qr-coder/ "QR Coder :: Firefox 附加组件")这种用右键的能对所有页面生效。

**Comment by zhcong** [comment]
你好，在[该页面](https://addons.mozilla.org/zh-CN/firefox/addon/qr-coder/)下，我的浏览器的QR Coder 和本插件都不能使用。

**Comment by ivysrono** [comment]
不好意思，不知道是我记错了还是56开始堵上了这个能用contentmenu的漏洞。
这就换成你的。
谢谢。

**Comment by ivysrono** [comment]
BTW, 能在 amo 地址栏上不显示图标么？

**Comment by zhcong** [comment]
能，在代码中加个过滤就行，`eventPage.js`文件改动如下

> `function check(table_id,data,tab){
	if(tab.url.indexOf("about:") || tab.url.indexOf("addons.mozilla.org")== 0){
		chrome.pageAction.hide(table_id);
	}else{
		chrome.pageAction.show(table_id);
	}
};`
我现在就去改

**Comment by zhcong** [comment]
哈哈，github和firefox插件商店已经更新了，amo地址栏不会显示了。

**Comment by ivysrono** [comment]
thanks
