### ISSUE TITLE
不支持微信公众号长地址？

### ISSUE THREAD

**Issue by ivysrono** [zhcong/firefox-qrcoder#2]
不支持：
https://mp.weixin.qq.com/s?__biz=MzU2MTA0ODU4NQ==&mid=2247484006&idx=1&sn=29fbe6ff9123fb9f97d71c9ddf4f0dd9&chksm=fc7fff00cb087616f1d10e28f57893a15e05b7ef3254c181b5d836e53281508d8c19438625a2&scene=21
![default](https://user-images.githubusercontent.com/2649544/31384586-258fab7a-adf2-11e7-8114-82fb9c81a78d.png)

支持：
https://mp.weixin.qq.com/s/LFGmtgZkOhxATpgwwBIAGw
![default](https://user-images.githubusercontent.com/2649544/31384593-2cf7a0ac-adf2-11e7-845e-3991cb8e8b51.png)

**Comment by zhcong** [comment]
你好，是使用的第三方QR码的生成库有问题，现在已经修复了。

**Comment by ivysrono** [comment]
1.4 great

**Comment by ivysrono** [comment]
还是有不支持的：
https://raw.githubusercontent.com/ivysrono/UpgradeMixedContentBlacklist/master/Blacklist.json
点了毫无反应。
版本：1.5

**Comment by zhcong** [comment]
你好，这个页面因为是特殊页面(其实是个json文件)所以遇到了和AMO页面一样的权限问题，你可以在该页面的父页面通过在链接处右键弹出的菜单中使用“生成选中链接的二维码”来生成二维码，就是在父页面生成这个地址的二维码。
这个页面非常特殊，firefox自带的截图插件在这个页面也不能工作。我在考虑通过其他特殊方式显示这些特殊页面。

**Comment by ivysrono** [comment]
原来如此，谢谢指点。
