### ISSUE TITLE
能不能把二维码放在图标下方啊

### ISSUE THREAD

**Issue by leitwolf** [zhcong/firefox-qrcoder#3]
在地址栏内点击生成的时候能不能直接在图标的下方直接弹出呢。
感觉这样不会破坏原来的浏览体验。
![tim 20171115120507](https://user-images.githubusercontent.com/1720546/32818293-490c3c18-c9fd-11e7-9315-f7f62cb94074.png)

**Comment by zhcong** [comment]
你好，想实现是出现在页面上的二维码，会在2.0版本中加入选项。

**Comment by Asteroids89** [comment]
老大，借问一下二维码直接在图标下方弹出的2.0版什么时间出来呢？谢谢

**Comment by zhcong** [comment]
2.0已发布到商店

**Comment by Asteroids89** [comment]
2.0版已经更新了，现在更好用了，感谢 @zhcong
